environment:
  seed: 0
  max_speed: 8.0
  max_torque: 2.0
  dt: 0.05
  g: 10.0
  m: 1.0
  l: 1.0
  obs_max: [1.0, 1.0, 8.0]
  act_dim: 1
  obs_dim: 3

controller:
  seed: 0
  temperature: 1
  n_timesteps: 20
  n_samples: 5000
  noise_sigma: 0.9